import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { AudioProvider } from "@/context/AudioContext";
import AudioControl from "@/components/AudioControl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-screen h-screen bg-black">
        <AudioProvider>
          <div className="flex w-full h-full p-2">
          <SideBar />
          {children}
          </div>
          <AudioControl />
        </AudioProvider>
      </body>
    </html>
  );
}
